### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by gabesullice** [kilimchoi/engineering-blogs#170]
Perhaps a languages section or perhaps just a note next to each blog so that one could just do a find on the page.

Something like:

Some Blog \<link\> (Go, Ruby)

**Comment by Githubcatadmin** [comment]
Ok

**Comment by kilimchoi** [comment]
It might not work for all blogs but may for some. I think a better idea is to tag per post. Maybe, I can add that feature on http://slicedham.co
