### ISSUE TITLE
Description and commentary

### ISSUE THREAD

**Issue by sindresorhus** [kilimchoi/engineering-blogs#241]
Would be useful to have a succinct description on each item on what the blog is about. Also, not everyone knows who all those people are, so just listing a name isn't very enticing.

Commentary would also be useful. This would be your (or the submitters) words on why it's worth a read. We've been doing this very successfully on `awesome-scifi` https://github.com/sindresorhus/awesome-scifi#cities-in-flight-1970-by-james-blish-40 and even have it as a requirement in the contributing guidelines https://github.com/sindresorhus/awesome-scifi/blob/master/contributing.md

**Comment by kilimchoi** [comment]
Will get to it when I have time.

**Comment by sindresorhus** [comment]
If it's not done it's not really appropriate to just close the ticket. People might be interested in contributing and would not discover it if it's closed.

**Comment by Loetn** [comment]
Sometimes brief won't be that brief. Tags are maybe simpler. And you can scan the page more quickly.

**Comment by duckspeaker** [comment]
This isn't suggested reading though. It's a list of engineering blogs. If you don't recognize someone's name, you can simply click on the link to their blog to get a better sense of what they do - or google them.
The whole point of this list is discovery.
