### ISSUE TITLE
Mark blogs that are not being updated anymore

### ISSUE THREAD

**Issue by pkafel** [kilimchoi/engineering-blogs#244]
Hey,

I think that for many people who are visiting this awesome repo it would be useful to have some information which blogs are dead and which are still being updated. If someone is looking for blog with info about newest technologies this would help. 

As an example Stephen Colebourne's [blog](http://blog.joda.org) is really cool however the last update was at the end of last year.

**Comment by kilimchoi** [comment]
Sure. I will actually incorporate these into http://slicedham.co Thanks!
