### ISSUE TITLE
engineering-blogs doesn't have short description of repository

### ISSUE THREAD

**Issue by meisyal** [kilimchoi/engineering-blogs#277]
Hi, all.

First of all, I would like to say thank you so much @kilimchoi for creating this awesome project. You are awesome. And amazing contributors too. I gave an issue to this repository regarding there isn't short description of engineering-blogs (it appears at the top of the repository). The ```README.md``` exists. The website (http://www.slicedham.co/) exists too. Do you any idea giving the short description (website is optional) for this repository?

Thank you for your attention.

**Comment by kilimchoi** [comment]
You mean like the short description of what this repo is about? I feel like it's pretty self-explanatory. It's just a compiled list of blogs on software development. If you have any ideas on anything I should add, feel free to let me know!

**Comment by meisyal** [comment]
Yes, it is. Short description of what this repo is about. In my opinion, it should be added. I know that's already explained on ```README.md```. It's pretty self-explanatory too, like you said. Sorry, this is the dumbest issue I have ever given.

I don't have any ideas right now. Thanks for asking, I will tell you if there is something to add.

**Comment by duckspeaker** [comment]
@kilimchoi Set the repo description to "A curated list of engineering blogs.", the url to http://www.slicedham.co/, and call it a day?

**Comment by kilimchoi** [comment]
done.

**Comment by duckspeaker** [comment]
I meant the description and website of the repo, not in the readme.

**Comment by meisyal** [comment]
Thank you :+1:
