### ISSUE TITLE
Adding stargazers to mailing list without consent?

### ISSUE THREAD

**Issue by jdpedrie** [kilimchoi/engineering-blogs#295]
I got an email from you via mailchimp. While I'm impressed that you were able to get a ~5000 person list into their system with such dubious sourcing, I'm mostly annoyed that you added me to a mailing list at all without me opting in. Shady move.

**Comment by kilimchoi** [comment]
I didn't intent to be intrusive in any way. The email was just a way to thank everyone who has contributed to the repo in any meaningful way. I apologize if it was something you didn't want to read. Also, no one on the list will be subscribed to the mailing list anymore. It was just one-off email.
