### ISSUE TITLE
Can I suggest to remove "Raymond Chen"

### ISSUE THREAD

**Issue by kavehmz** [kilimchoi/engineering-blogs#300]
"Raymond Chen" or http://blogs.msdn.com/rss.aspx is generating about 5k entries per week.

About 3 times more than all other entries in the list altogether.

I can fork and remove it only for myself of course.

But I was wondering is any one is actually following and reading this one and it adds any value to this nicely curated list.

**Comment by duckspeaker** [comment]
Yeah looks like the rss url is incorrect: http://blogs.msdn.com/rss.aspx. It's getting the rss for all of blogs.msdn.com.
