### ISSUE TITLE
Question on quality of submissions

### ISSUE THREAD

**Issue by jacobbednarz** [kilimchoi/engineering-blogs#309]
Hey,
I've made a few contributions here and I've enjoyed adding some of these to my personal feed of blogs to watch however of late it seems to me that there isn't a quality standard that is being imposed here and some of the links that are getting in are less than useful (mainly personal blogs which appear to be just after some click throughs) 

I'm wondering whether this is intended to just be a large link base of blogs that exist on the internet or whether it was aiming to provide more of a "quality" blogs to follow. 

Interested in your thoughts on this.

**Comment by jacobbednarz** [comment]
...and just as I submit this @kilimchoi knocks back a submission via #308 for not enough technical content :stuck_out_tongue_winking_eye:

**Comment by kilimchoi** [comment]
Hi @jacobbednarz I try hard to reject PR containing links to the blogs that have low quality stuff. But sometimes low quality links seeps in. I guess one way to prevent this problem is, do a clean up regularly to remove links that don't contain anything interesting or haven't published anything in years.

**Comment by jacobbednarz** [comment]
> I try hard to reject PR containing links to the blogs that have low quality stuff.

Just to confirm, I'm incredibly grateful for this project and you've done an awesome job! I just wanted to see whether this _was_ an aim of the project :)

> This is what I'm trying to fix with slicedham. I only approve posts that are not marketing spam. I think that's a much better solution than relying on our opml file and uploading to the feed reader.

Cool! I didn't realise this as I was using my own reader. Will give it a whirl!

**Comment by prashantpandeyfun10** [comment]
Hi..Could you check the quality of https://potentialmind.wordpress.com/2015/08/03/all-about-competitive-programing/ and include it here.

**Comment by kilimchoi** [comment]
@prashantpandeyfun10 I think you can make a PR for it.

**Comment by prashantpandeyfun10** [comment]
Sure! Few Minutes.Please see the quality of the site and take appropriate decision.Thanks

**Comment by kilimchoi** [comment]
It looks good. Please make a pull request with the addition.

**Comment by prashantpandeyfun10** [comment]
I have requested a PR ..have a look.

**Comment by kilimchoi** [comment]
I don't see your pull request. Nothing is open on Pull request right now. @prashantpandeyfun10
