### ISSUE TITLE
generate_opml script and non-ascii chars

### ISSUE THREAD

**Issue by aoozdemir** [kilimchoi/engineering-blogs#328]
I ran the script by typing `ruby generate_opml.rb` on cmd with Rails but after it's done, non-ascii chars were processed incorrectly, like 
`Radim Řehůře` turn into `Radim ┼ÿeh┼»┼Öek`,
`Oona Räisänen` turn into `Oona R├ñis├ñnen` and so on.

Did I somehow run the script wrong?

**Comment by duckspeaker** [comment]
No you're running it correctly though I'm not seeing that issue. What version of ruby are you using?

**Comment by aoozdemir** [comment]
```
ruby:
  version:    ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

rails:
  version:    Rails 4.1.10
```

Also, I did try adding `# encoding: UTF-8` line at the beginning of the file, and changing the font of console, since it might affect. It didn't work.

**Comment by duckspeaker** [comment]
It might be a windows-related issue. See if any of the solutions here work: http://stackoverflow.com/questions/9432511/ruby-utf-8-encoding-doesnt-work-in-windows-even-with-magic-comment

Also, you don't need rails to run it.

**Comment by aoozdemir** [comment]
Thank you for that. I'll check it tomorrow and feedback. :+1:

**Comment by aoozdemir** [comment]
Yeap. Changing the  the codepage in the console to unicode `chcp 65001` solved the problem. Thanks!
