### ISSUE TITLE
awesome bot ssl issues

### ISSUE THREAD

**Issue by kaizensoze** [kilimchoi/engineering-blogs#465]
> 1. https://hashrocket.com/blog SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
> 2. https://wyeworks.com/blog/ SSL_connect SYSCALL returned=5 errno=0 state=unknown state

Awesome bot seems to be having some issues with ssl (https://github.com/dkhamsing/awesome_bot/pull/56) causing the build to fail.

Might want to disable travis integration for now.

**Comment by kilimchoi** [comment]
I actually thought that these websites have configured ssl incorrectly. We can just ignore SSL issues for now. It's still pretty useful for catching duplicates or redirects.

**Comment by kaizensoze** [comment]
It's more an issue with ruby than the given server's ssl config.

https://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat
https://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read

**Comment by kilimchoi** [comment]
Removed travis
