### ISSUE TITLE
OPML file parse error

### ISSUE THREAD

**Issue by jjoewy** [kilimchoi/engineering-blogs#503]
Hi guys,

Has somebody experienced a parse error when trying to import the opml file into a reader? I've given a try to import it into Feedly but got a parse error. To troubleshoot  itI've tried http://codebeautify.org/opmlviewer.

Regards,
Alex

**Comment by kaizensoze** [comment]
The latest opml file imports ok for me in both feedly and digg reader.

**Comment by kaizensoze** [comment]
I realize my "works on my local" reply isn't particularly helpful, but others chime in if you're also having any issues importing the opml file.

**Comment by hai-ld** [comment]
Worked for me (just imported to Feedly two days ago)

**Comment by kaizensoze** [comment]
I'm going to close this for now. Feel free to post step by step instructions on reproducing the issue if you're still seeing it.
