### ISSUE TITLE
SlicedHam website is down

### ISSUE THREAD

**Issue by meisyal** [kilimchoi/engineering-blogs#518]
SlicedHam is a website that curated engineering blog from this repository. It's been two days since I accessed SlicedHam website (http://www.slicedham.co). The message that I got from browser is

> **Application Error**
An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

I hope there is a news what current state of SlicedHam website.

**Comment by rajadain** [comment]
Bump

**Comment by kilimchoi** [comment]
Sorry guys, I've shut down the site due to low usage.

**Comment by rajadain** [comment]
Ah, thanks for the update. I wasn't a regular viewer, but appreciated it being up there. Thanks for keeping this repo open though. Maybe one day I'll make something from this
