### ISSUE TITLE
Name change "awesome-engineering-blog"

### ISSUE THREAD

**Issue by jsimnz** [kilimchoi/engineering-blogs#53]
The whole new trend of "awesome lists" have been making a pretty big impact, so why not ride the coat tail on that one.

Also people would better know what this is from just the title.

To be honest, I first read the title on HN and thought it was some blogging platform or theme for existing blogging platform geared towards the style of engineering blogs.

Just a thought

**Comment by kilimchoi** [comment]
Can you link me to another awesome list?

**Comment by jsimnz** [comment]
Here is a awesome list of awesome lists :smile: 

https://github.com/bayandin/awesome-awesomeness
