### ISSUE TITLE
How to add posts not written in English

### ISSUE THREAD

**Issue by ts-3156** [kilimchoi/engineering-blogs#556]
Hello,

I want to add blogs not written in English ( e.g. http://techblog.yahoo.co.jp/ ).
May I add this blog to README.md or README.ja.md ?

**Comment by kaizensoze** [comment]
@kilimchoi Thoughts on this?

**Comment by kilimchoi** [comment]
@ts-3156 @kaizensoze Let's create README.ja.md and add it there?

**Comment by kaizensoze** [comment]
Sounds good. I'll update the generate script once the .ja.md file is added.

**Comment by ts-3156** [comment]
Thank you for replying. I will create a pull request to add it next Sunday.
