### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by Munawwar** [kilimchoi/engineering-blogs#599]
Hi. The following is regarding the xmlUrl attribute of some blogs in the opml file (I am listing only the blog host name to reduce issue noise):

Corrections
-----------
engineering.fundingcircle.com -> https://engineering.fundingcircle.com/feed.xml
deferpanic.com -> Remove trailing slash
carlosbecker.com -> http://carlosbecker.com/feed.xml
practicingruby.com -> https://www.practicingruby.com/feed.xml
yifan.lu -> remove trailing slash
developer.okta.com -> http://developer.okta.com/feed.xml
robots.thoughtbot.com -> https://robots.thoughtbot.com/feed.xml
developer.apple.com -> https://developer.apple.com/swift/blog/news.rss

Can't find (404 error)
----------------
https://www.buzzfeed.com/techblog
tech.taskrabbit.com
labs.opendoor.com
tech.trivago.com
www.simple.com

Unparsable?
-----------
nshipster.com

Unreachable domains
-----------
techblog.badoo.com -> Socket hang up
eng.kifi.com -> blog shutdown
arslan.io: Domain does not exist
blog.humblecoder.com -> domain suspended?
www.technotalkative.com -> domain suspended?

What to do?
-----------
segment.com -> https://segment.com/blog/atom.xml. However non-engineering stuff is mixed into the feed as well I think.

**Comment by kaizensoze** [comment]
techblog.badoo.com seems to be working ok, but I'll look into everything else. Thanks for the detective work!

**Comment by Munawwar** [comment]
Here is one more - wyeworks.com rssUrl seems to redirect to an HTML page now.

**Comment by kaizensoze** [comment]
Done: #606

**Comment by Munawwar** [comment]
Cool. BTW I've just used your awesome list to start devblogsdaily.com (It's still in the works)

**Comment by Munawwar** [comment]
devblogsdaily.com is up. I've mentioned this repo and you at http://www.devblogsdaily.com/about.html.

**Comment by kaizensoze** [comment]
Thanks for the mention!
