### ISSUE TITLE
Base link leads to 502 bad gateway

### ISSUE THREAD

**Issue by DeepAnchor** [kilimchoi/engineering-blogs#61]
dead link: https://lab.getbase.com/category/engineering/

**Comment by nagas** [comment]
Link should work again. There was some underlying problem with a connection between blog instance and AWS RDS. We are figuring it out with AWS Support.

**Comment by DeepAnchor** [comment]
looks good :+1:

**Comment by nagas** [comment]
@kilimchoi will you add your blog again? Or should I make another PR? :)

**Comment by kilimchoi** [comment]
Done.
