### ISSUE TITLE
Is there a Twitter accounts version of this?

### ISSUE THREAD

**Issue by bouiboui** [kilimchoi/engineering-blogs#619]
Because that would be awesome. Sorry if it's a bit off-topic.

If there isn't, I'd be happy to start one.

**Comment by kaizensoze** [comment]
Nope, but feel free to create one!

**Comment by meisyal** [comment]
I think there is @kaizensoze. How about this https://mobile.twitter.com/slicedham_tech?
The last update is on February, 2016.

**Comment by kilimchoi** [comment]
If anyone is interested in running it, feel free to let me know. Email me at choikilim1202 AT gmail.com

**Comment by bouiboui** [comment]
I've started a branch up in https://github.com/bouiboui/engineering-twitter/tree/feature/twitter
Any help is appreciated, I'm doing it alphabetically so you may not want to pick one of the first letters.

**Comment by kaizensoze** [comment]
This was a pretty ambitious endeavor. I'd include a link to it at the bottom of the README but it only goes up to D companies. Is it ok if we close this ticket since it doesn't directly pertain to this repo?

**Comment by bouiboui** [comment]
You're right, I got discouraged by then and hoped someone would take over 😋 
Maybe some day!

You can close this, thanks for asking.

**Comment by kaizensoze** [comment]
Alright, thanks!
