### ISSUE TITLE
Merge with sumodirjo/engineering-blogs

### ISSUE THREAD

**Issue by msolorzano** [kilimchoi/engineering-blogs#631]
Doing a quickly diff with this [readme](https://raw.githubusercontent.com/sumodirjo/engineering-blogs/master/README.md) I got as a result the lack of these blogs:

* 9gag
* airbrake
* avant
* backtrace
* banksimple
* betterworks
* branch
* captricity
* close.io
* cloudscaling
* coursera
* crowdbooster
* datafloq
* dataiku
* dchq.io
* elastic
* fastmail
* fluidinfo
* hubblehq
* icehouse
* import.io
* influxdata
* jelastic
* kaggle
* machinalis
* pagerduty
* pagico
* persiscope data
* phyramid
* raintank
* rea group
* reddit
* simulmedia
* smugmug
* starva
* stylight
* tellapart
* udacity
* workshape
* yammer
* zenpayroll

I didn't make the test if each of these blogs respect these guidelines: 
*For company blogs, make sure that 80% of content is technical (posts about interesting technical challenges, lessons they've learned, etc). No PR, self-promoting posts.
For individual blogs, as long as posts are mostly technical (not as strict with the ratio as the company one), I am happy to add them.*

Hope this could help :)

**Comment by kaizensoze** [comment]
Going to add the following:

Airbrake https://airbrake.io/blog/
Backtrace https://backtrace.io/blog/
Machinalis http://www.machinalis.com/blog/
Periscope Data https://www.periscopedata.com/blog
Raintank https://blog.raintank.io/
REA Group http://rea.tech/engineering/

The rest don't have enough technical posts.

**Comment by kaizensoze** [comment]
Added.

26cad81c5a95a9a4b2b7bfe68401812a4a50da8e
d04e6c29567fa192e422b0900ef11b70e4de0f7e
1e3b1dc3266d49051e3c1e0e788ef37d347ab772
cc3a01b7d5c8cb223c00a34c162ebb01750c9222
f01302a7bfe12928d149cc099fa68ccd076fc5a9
d7ef56019235d1a2bff9ebe7f9eda5ef54d417b5
