### ISSUE TITLE
Broken feeds

### ISSUE THREAD

**Issue by AeonZh** [kilimchoi/engineering-blogs#643]
The following feeds are not-valid/nonexistent/probably outdated:

AdRoll: [http://tech.adroll.com/feed.xml](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ftech.adroll.com%2Ffeed.xml) (not valid)
Made Tech: [http://www.madetech.com/feed](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.madetech.com%2Ffeed) (feeds not found)
Magnet.me: [https://labs.magnet.me/feed.xml](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Flabs.magnet.me%2Ffeed.xml) (site not found)
Microsoft: [https://engineering.microsoft.com/feed/](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fengineering.microsoft.com%2Ffeed%2F) (feeds not found)
Opendoor: [https://labs.opendoor.com/feed.xml](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Flabs.opendoor.com%2Ffeed.xml) (feeds not found)
Segment: [https://segment.com/blog/categories/engineering/atom.xml](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fsegment.com%2Fblog%2Fcategories%2Fengineering%2Fatom.xml) (found this [https://segment.com/blog/atom.xml](url), but did not check the point `For company blogs, make sure that 80% of content is technical (posts about interesting technical challenges, lessons they've learned, etc).`)
SRC:CLR: [https://blog.sourceclear.com/atom.xml](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fblog.srcclr.com%2Fatom.xml) (not valid)
theScore: [http://techblog.thescore.com/feed.xml](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ftechblog.thescore.com%2Ffeed.xml) (not valid)
Trivago: [http://tech.trivago.com/atom.xml](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ftech.trivago.com%2Fatom.xml) (feeds not found)
Zoosk: [https://about.zoosk.com/feed/](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fabout.zoosk.com%2Ffeed%2F) (feeds not found)

Blake Erickson: [http://blakeerickson.com/atom.xml](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fblakeerickson.com%2Fatom.xml) (feeds not found)
Jonathan Dekhtiar: [https://www.born2data.com/feed.xml](http://feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.born2data.com%2Ffeed.xml) (updated: [https://www.born2data.com/feed_atom.xml](url))
RocksDB: [http://rocksdb.org/blog/rss](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Frocksdb.org%2Fblog%2Frss) (updated: [http://rocksdb.org/feed.xml](url))

**Comment by kaizensoze** [comment]
Thanks, I'll go through and update them.

**Comment by kaizensoze** [comment]
Ok, all cleaned up.
