### ISSUE TITLE
Add contributing guidelines 

### ISSUE THREAD

**Issue by shameerc** [kilimchoi/engineering-blogs#66]
Great list, thanks for creating this. How/What can I contribute this list? 
It would be great if you can add contributing guidelines like [contributing.md](https://github.com/sindresorhus/awesome/blob/master/contributing.md). This will help others to understand what is acceptable and what is not. I basically would like to add [PHPToday](https://www.phptoday.org/) to this list if you think that's acceptable :)
Cheers

**Comment by kilimchoi** [comment]
Done.
