### ISSUE TITLE
Also sort the blogs according to the tech that each company uses.

### ISSUE THREAD

**Issue by gopalgoel** [kilimchoi/engineering-blogs#749]
For e.g. List of blogs of companies that uses MongoDB primarily at production, etc.

**Comment by kilimchoi** [comment]
That is going to be extremely challenging unless crowd curates it themselves. Imagine going through thousands of blogs yourself and having to figure out what tech stack they use. It's a lot of man hours.

**Comment by gopalgoel** [comment]
True that. We can use [stackshare](www.stackshare.io) instead to get some insight about tech usage.
