### ISSUE TITLE
Fix incorrect blogs and feeds (list included)

### ISSUE THREAD

**Issue by leominov** [kilimchoi/engineering-blogs#753]
Hello

### Asos (http://techblog.asos.com/feeds/posts/default)
```
HTTP/1.1 301 Moved Permanently
Location: http://www.asos.com
```
Seems like it's gone

### Avenue Code (http://blog.avenuecode.com/rss/)
http://blog.avenuecode.com/rss.xml

### Airbnb (http://nerds.airbnb.com/feed/)
https://medium.com/feed/airbnb-engineering

### Deis (https://deis.com/sitemap.xml)
https://deis.com/feed.xml

### DeferPanic (https://deferpanic.com/blog/index.xml/)
https://deferpanic.com/blog/index.xml

### Funding Circle (https://engineering.fundingcircle.com/blog/feed.xml)
https://engineering.fundingcircle.com/feed.xml

### Holiday Extras (http://navigationshilfe.t-online.de/dnserror?url=http://hungrygeek.holidayextras.co.uk.atom/)
Actually http://tech.holidayextras.co.uk, but no feeds found

### Huddle (http://tldr.huddle.com/atom.xml)
```
HTTP/1.1 404 Not Found
```

### Just Eat (http://navigationshilfe.t-online.de/dnserror?url=http://tech.just-eat.com.atom/)
Actually http://tech.just-eat.com, but no feeds found

### Linkedcare (http://blog.linkedcare.com/rss)
Couldn't resolve host 'blog.linkedcare.com'

### Hostinger (https://www.hostinger.com/blog/feed.xml)
https://www.hostinger.com/blog/feed/

### Lookout (http://hackers.lookout.com/atom.xml)
```
HTTP/1.0 400 Bad Request
```

### LINE (http://developers.linecorp.com/blog/?feed=rss2)
https://engineering.linecorp.com/en/blog/rss2

### Monsanto (http://engineering.monsanto.com/feed.xml)
Found but not a feed

### Periscope Data (https://www.periscopedata.com/blog/atom.xml)
Duplicate of Periscope, should be deleted

### Periscope (https://www.periscopedata.com/blog/atom.xml)
```
HTTP/1.1 404 Not Found
```

### Quora (https://engineering.quora.com/rss)
```
HTTP/1.1 403 Forbidden
```

### Robert Elder Software (http://navigationshilfe.t-online.de/dnserror?url=http://blog.robertelder.org.atom/)
Actually http://blog.robertelder.org, but no feeds found

### Raintank (https://blog.raintank.io/rss/)
Raintank should be renamed to Grafana, I think.
```
HTTP/1.1 301 Moved Permanently
Location: https://grafana.com/blog/rss/
```
Actually https://grafana.com/blog/blog/index.xml

### WSO2 (http://wso2.com/node/37573/atom/feed)
```
HTTP/1.1 404 Not Found
```

### Andrey Akinshin (http://aakinshin.net/en/rss.xml)
http://aakinshin.net/rss.xml

### Blake Erickson (http://navigationshilfe.t-online.de/dnserror?url=http://blakeerickson.com.atom/)
https://blog.blakeerickson.com/posts.rss

### Axel Rauschmayer (http://www.2ality.com/feeds/posts/default)
http://feeds.feedburner.com/2ality

### Daily JS (http://dailyjs.com/rss/)
```
HTTP/1.1 503 Service Unavailable
```

### DataRadar.io (https://www.dataradar.io/rss/)
Couldn't resolve host 'www.dataradar.io'

### Clay McLeod (http://blog.claymcleod.io/atom.xml)
```
HTTP/1.1 403 Forbidden
```

### Dean Hume (http://navigationshilfe.t-online.de/dnserror?url=http://deanhume.com.atom/)
https://feeds.feedburner.com/DeanHumesBlog

### Edan Kwan (http://navigationshilfe.t-online.de/dnserror?url=http://blog.edankwan.com.atom/)
Actually http://blog.edankwan.com, but no feeds found

### Chinmaya Kr. Patanaik (http://chinmayapatanaik.com/atom.xml)
Seems like it's gone

### Jonathan Dekhtiar (https://www.born2data.com/feed_atom.xml)
http://www.born2data.com/feed_atom.xml

### Nick Galbreath (http://navigationshilfe.t-online.de/dnserror?url=http://www.client9.com.atom/)
https://www.client9.com/index.xml

### Sebastian Barthel (http://journerist.com/rss/)
```
HTTP/1.1 502 Bad Gateway
```

### Grammarly (http://tech.grammarly.com/blog/rss.xml)
Timeout

### Monetate (http://engineering.monetate.com/feed/)
Timeout

**Comment by leominov** [comment]
Found another batch of bugs. Create PR?

**Comment by kaizensoze** [comment]
These should be resolved.

627595c1e8842e8b3ccf803e768cdbb7ce845f45
682805900bd884c52e4c15d68ffdcc5ede987af8
ef94aa5139c2d5763924c433a603a32afbb31ebd
d5f98309d4cc9220ba60286954d51d2368b4f048
84b76f895ff6af1aefea4e68d9c22d1f9d14021f
cda9da501f7cd71d54cc5364d917af036c475667
d09a8708c74bcd6d113a24ff720d760c249b5a97

**Comment by leominov** [comment]
Looks good, thanks
