### ISSUE TITLE
Wrong feed in https://benmccormick.org/rss/

### ISSUE THREAD

**Issue by juanpabloaj** [kilimchoi/engineering-blogs#765]
The right feed of http://benmccormick.org/ is

    https://benmccormick.org/rss/

the actual feed in the opml file is

    xmlUrl="http://benmccormick.org/2017/05/28/mariana-syntax-atom/

https://github.com/kilimchoi/engineering-blogs/blob/36272f76d61a1c3fd71c5b96b977802eb0a33efa/engineering_blogs.opml#L365

**Comment by kaizensoze** [comment]
Updated: 0b5635049ff414a2cc28c99f2f5ab38a54c213a9
