### ISSUE TITLE
https://entries-by-votes.now.sh/

### ISSUE THREAD

**Issue by juanpabloaj** [kilimchoi/engineering-blogs#774]
Hi,
 I started this project 

https://entries-by-votes.now.sh/
https://github.com/juanpabloaj/entries-by-votes

The page show the entries of the feeds of engineering-blogs order by Hacker News and Reddit votes.

Maybe can be useful or interesting for someone.

**Comment by kaizensoze** [comment]
Going to close this since it doesn't really go with the current presentation.
