### ISSUE TITLE
Request for permission on master

### ISSUE THREAD

**Issue by wcerfgba** [kilimchoi/engineering-blogs#814]
Hi @kaizensoze (as currently most active committer) and @kilimchoi (as repository owner),

I'd like to ask for permission to push to master so I can help out with maintaining this great repo.

I've gone through and reviewed all the open PRs and am happy to help their corresponding contributors get these merged in. Additionally, I have wanted to establish a similar list myself a while ago and started amassing a list of blogs, which I will work on putting PRs in for adding to the list.

I think this is a great resource and would love to help it grow. ❤️

**Comment by kilimchoi** [comment]
Sorry we are not giving out master access right now.
