### ISSUE TITLE
Is there a way to RSS subscribe all of them at once?

### ISSUE THREAD

**Issue by Akuukis** [kilimchoi/engineering-blogs#857]
Is there a way to RSS subscribe all of them at once?

**Comment by kaizensoze** [comment]
You should be able to import the opml file. What rss reader do you use?

**Comment by Akuukis** [comment]
I use Mozilla thunderbird

**Comment by kaizensoze** [comment]
This should do the trick: http://www.ubuntubuzz.com/2017/04/how-to-import-opml-of-rss-feeds-in-thunderbird.html

**Comment by Akuukis** [comment]
Thanks, that did the trick. Although at start I was confused but had only to wait - it took more than 10 minutes for any article to show up. Most likely hard to handle such list :)
