### ISSUE TITLE
A few feedbacks

### ISSUE THREAD

**Issue by SiqingYu** [kilimchoi/engineering-blogs#924]
These blogs are either moved or down:
* Data Artisans (https://data-artisans.com) now becomes Ververica (https://www.ververica.com/). The old site is down.
* https://deferpanic.com/blog/index.xml/ is replaced with https://nanovms.com/ which doesn't have an RSS feed
* DoorDash engineering blog is now at https://doordash.engineering/
* http://tech.gilt.com/ is now https://tech.hbc.com/ which doesn't have an RSS feed
* The company Grouper joingrouper.com shut down in 2016
* http://intentmedia.com/ is now at intent.com, but their new blog doesn't have any post yet.
* The Intercom blog feed is now at https://www.intercom.com/blog/engineering/feed
* http://sartorialscience.myntrablogs.com/ is down.
* http://pullreview.com/ is down. See: http://blog.8thcolor.com/en/2018/02/the-end/
* REA Group tech blog is now at https://www.rea-group.com/category/tech/
* Redbubble tech blog is now at https://medium.com/feed/redbubble/tagged/tech/
* Scrunch tech blog is now at https://blog.scrunch.com/product-updates/tag/tech-blog/rss.xml
* Snyk blog feed is now at https://snyk.io/blog/feed/
* Stormpath joined Okta and shut down.
* Target tech blog is now at https://tech.target.com/feed.xml
* VersionEye has shut down. See: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
* Vine has been archived.
* wearewizards.io is down.
* Wolox is now at https://medium.com/wolox-driving-innovation
* https://engineering.zenefits.com/feed/ is no longer available.

These blogs are not engineering blogs but instead product promotion or non-technical blogs; they shouldn't be in the list:
* https://gocardless.com/blog
* https://developers.livechatinc.com/blog/
* https://devs.mailchimp.com/blog
* http://blog.mandrill.com/
* https://www.maptiler.com/blog/
* https://www.memsql.com/blog/
* https://mixmax.com/feed/
* https://blogs.nvidia.com/
* https://developer.okta.com/
* https://www.periscopedata.com/blog
* https://postmarkapp.com/blog
* https://www.pubnub.com/blog/
* https://realm.io/blog/
* https://www.runtastic.com/blog/
* https://developer.salesforce.com/blogs/
* https://www.semantics3.com/blog/
* https://www.sharethis.com/feed/
* https://www.stridenyc.com/blog

**Comment by kilimchoi** [comment]
@SiqingYu Thanks will update
