### ISSUE TITLE
Codelitt Blog URL is Invalid.

### ISSUE THREAD

**Issue by vyasriday** [kilimchoi/engineering-blogs#953]
The url [https://www.codelitt.com/blog](https://www.codelitt.com/blog) is not working. It says not found. The right URL is medium.com/codelitt.

**Comment by vyasriday** [comment]
I will update the URL once I get hold of my system. Meanwhile anyone wants to take it, feel free to do so.

**Comment by kilimchoi** [comment]
@vyasriday thanks will update
