### ISSUE TITLE
Starting a newsletter with curated blog posts

### ISSUE THREAD

**Issue by kilimchoi** [kilimchoi/engineering-blogs#972]
Hi, 

I realized that the list has gotten way too long and I'm seeing a lot of crappy posts in my reader. 
I'm planning to handpick the best 3-5 blog posts a week to share with you guys. Make sure to subscribe to https://devweekly.substack.com/p/coming-soon?r=6a2p&utm_campaign=post&utm_medium=web&utm_source=copy if you are interested.

**Comment by mtimofiiv** [comment]
It's a nice list you have here. But you need to stop opting people to this newsletter in because they starred your repo. That's called spam.

**Comment by sibartlett** [comment]
Agreed, I did not appreciate receiving unsolicited email.

**Comment by sibartlett** [comment]
Please don’t spam everyone who starred this project. Also, instead of deleting comments, why don’t you own up and apologize.

**Comment by kilimchoi** [comment]
> Please don’t spam everyone who starred this project. Also, instead of deleting comments, why don’t you own up and apologize.

Hey @sibartlett I won't be spamming people anymore. Starting any kind of project is hard and to kickstart this newsletter, I had to at least people know about it. You have the option to unsubscribe if you do not want to get the email anymore. If you unsubscribe, I won't be sending you any more emails. You have my word.
