### ISSUE TITLE
Incompatible nokogiri and ruby versions

### ISSUE THREAD

**Issue by pabuisson** [kilimchoi/engineering-blogs#976]
Hello there,

I wanted to suggest a new engineering blog to the repo, however, when trying to `bundle install` to update the OPML file, I got an error message saying that:

```
Fetching gem metadata from https://rubygems.org/..................
Fetching version metadata from https://rubygems.org/.
nokogiri-1.10.4 requires ruby version >= 2.3.0, which is incompatible with the current version, ruby 2.2.7p470
```

Which is true. The issue has likely been introduced by commit https://github.com/kilimchoi/engineering-blogs/commit/d33b0aa1dc6d994a412b63989569e1efaa7808c5 which bumped nokogiri to a more recent version.

I'm very willing to make a PR for this, only question is: are we okay with bumping Ruby version to something (a lot) more recent like 2.7.0 (and a more recent bundler too at the same time)? Or we can also revert the nokogiri update, but it seems like a less optimal solution. Let me know what you think.

**Comment by kilimchoi** [comment]
we can bump the ruby version. feel free to make a pr. thanks!
