### ISSUE TITLE
Will Dev Weekly keep publishing? 

### ISSUE THREAD

**Issue by SiqingYu** [kilimchoi/engineering-blogs#996]
I know https://github.com/kilimchoi/engineering-blogs/issues/972.
But I think Dev Weekly is a great idea. Many developers might love it.
@kilimchoi Please continue publishing the newsletters. The readers can subscribe to Substack with RSS apps.

**Comment by kilimchoi** [comment]
Hi @SiqingYu thanks for your kind words. 
Last week's issue was a bit delayed due to personal matters. I will send out the issue as usual on Saturday. Thanks!
